sudo: required

env:
  - ARCH_TRAVIS_CLEAN_CHROOT=1 ARCH_TRAVIS_CONFIRM_YES=1

language: cpp
notifications:
  email: false

compiler:
  - gcc

arch:
  packages:
    - gcc
    - cmake
    - extra-cmake-modules
    - vulkan-headers
    - vulkan-hpp
    - vulkan-intel
  script:
    - sudo sh ./ci/install_vulkan_sdk.sh
    - sudo sh ./ci/travis_build.sh

script:
  - bash ci/arch-travis/arch-travis.sh