sudo: required

git:
    submodules: false

before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    
env:
  - ARCH_TRAVIS_CLEAN_CHROOT=1 ARCH_TRAVIS_CONFIRM_YES=1

notifications:
  email: false

language: c

compiler:
    - gcc
    - clang

arch:
  before_install:    
    - gpg --recv-keys 11E521D646982372EB577A1F8F0871F202119294
  packages:
    - gcc
    - clang
    - clang-tools-extra
    - libc++
    - cmake
    - libxcb
    - vulkan-intel
    - vulkan-icd-loader
    - python
    - conan
  script:
    - sudo sh ./ci/travis_build.sh $CC

script:
  - bash ci/arch-travis/arch-travis.sh
